version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trs-ftp-server_filebrowser_1
      APP_PORT: 80

  filebrowser:
    image: docker.io/filebrowser/filebrowser
    container_name: trs-ftp-server_filebrowser_1
    restart: on-failure
    command: --database /srv/.filebrowser.db --noauth
    volumes:
      - ${APP_DATA_DIR}/data/srv:/srv
    tmpfs:
      - /config

  ftp:
    image: docker.io/garethflowers/ftp-server
    container_name: trs-ftp-server_ftp_1
    restart: on-failure
    ports:
      - "20:20"
      - "21:21"
      - "40000:40000"
      - "40001:40001"
      - "40002:40002"
      - "40003:40003"
      - "40004:40004"
      - "40005:40005"
      - "40006:40006"
      - "40007:40007"
      - "40008:40008"
      - "40009:40009"
    volumes:
      - ${APP_DATA_DIR}/data/srv:/home/admin
    environment:
      FTP_USER: admin
      FTP_PASS: ${APP_PASSWORD}
      PUBLIC_IP: 192.168.1.2
